name: Build Spring Boot with Gradle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Permissão Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Preparar Configuração da Aplicação
        run: |
          mkdir -p ${{ secrets.FOLDER_PATH }}
          cp ${{ secrets.FILE_PATH }}

      - name: Build + Testes + JaCoCo
        run: ./gradlew clean build jacocoTestReport --no-daemon --info

      - name: Usuário
        run: echo "BUILD EXECUTADO POR:" ${{ github.actor }}
